// Package podbuilder isolates the ONE change edge-scheduler needs so pywaggle2 can
// read node identity/GPS: give every scheduled plugin container access to the
// existing `wes-identity` ConfigMap via EnvFrom.
//
// This mirrors the real container-construction block in
//   edge-scheduler/pkg/nodescheduler/resourcemanager.go
//     func (rm *ResourceManager) createPodTemplateSpecForPlugin(...)  (~L877)
// where the plugin container is built as:
//     containers := []apiv1.Container{{
//         Name: pr.Plugin.Name, Image: ..., Args: ..., Env: envs,
//         Resources: ..., VolumeMounts: volumeMounts,
//     }}
//
// The ONLY functional change is the added EnvFrom referencing wes-identity
// (Optional=true so a node whose WES hasn't yet created the ConfigMap still
// schedules). We reproduce enough of the surrounding shape (the standard WAGGLE_*
// Env, the data-config volumeMount) to prove the change is additive and does not
// disturb what's already injected.
//
// Uses the SAME k8s.io/api version as upstream (v0.23.1) so the types are identical.
package podbuilder

import (
	apiv1 "k8s.io/api/core/v1"
)

// WESIdentityConfigMap is the existing ConfigMap generated by
// waggle-edge-stack update-stack.sh (envs from configs/wes-identity.env). Today it
// carries WAGGLE_NODE_{ID,VSN}; with the companion gen-wes-identity.sh change it
// also carries WAGGLE_NODE_{GPS_LAT,GPS_LON,MOBILITY}. The scheduler does not need
// to know the keys -- EnvFrom projects whatever the ConfigMap holds.
const WESIdentityConfigMap = "wes-identity"

func booltoPtr(b bool) *bool { return &b } // mirrors upstream helper

// standardPluginEnv is an abbreviated copy of the env list the real builder injects
// (resourcemanager.go ~L589-L858). Kept short but representative; the point of the
// test is the EnvFrom addition, not re-listing every var.
func standardPluginEnv() []apiv1.EnvVar {
	return []apiv1.EnvVar{
		{Name: "WAGGLE_PLUGIN_HOST", Value: "wes-rabbitmq.default.svc.cluster.local"},
		{Name: "WAGGLE_GPS_SERVER", Value: "wes-gps-server.default.svc.cluster.local"},
		{Name: "WAGGLE_SCOREBOARD", Value: "wes-scoreboard.default.svc.cluster.local"},
		{Name: "WAGGLE_APP_ID", ValueFrom: &apiv1.EnvVarSource{
			FieldRef: &apiv1.ObjectFieldSelector{FieldPath: "metadata.uid"}}},
	}
}

// standardVolumeMounts mirrors the always-present mounts (resourcemanager.go ~L718).
func standardVolumeMounts() []apiv1.VolumeMount {
	return []apiv1.VolumeMount{
		{Name: "uploads", MountPath: "/run/waggle/uploads"},
		{Name: "waggle-data-config", MountPath: "/run/waggle/data-config.json", SubPath: "data-config.json"},
	}
}

// BuildPluginContainer constructs the plugin container exactly as the scheduler
// does, WITH the node-identity change applied: EnvFrom -> wes-identity (Optional).
//
// This is the drop-in shape for the upstream container literal: add the EnvFrom
// field alongside the existing Env/VolumeMounts.
func BuildPluginContainer(name, image string, userEnv []apiv1.EnvVar) apiv1.Container {
	envs := append([]apiv1.EnvVar{}, userEnv...) // user env first (upstream comment)
	envs = append(envs, standardPluginEnv()...)

	return apiv1.Container{
		Name:  name,
		Image: image,
		Env:   envs,
		// >>> THE CHANGE <<< : project the existing wes-identity ConfigMap so the
		// plugin gets WAGGLE_NODE_{ID,VSN,GPS_LAT,GPS_LON,MOBILITY} without the
		// scheduler hard-coding any of them. Optional so absence != scheduling failure.
		EnvFrom: []apiv1.EnvFromSource{
			{ConfigMapRef: &apiv1.ConfigMapEnvSource{
				LocalObjectReference: apiv1.LocalObjectReference{Name: WESIdentityConfigMap},
				Optional:             booltoPtr(true),
			}},
		},
		VolumeMounts: standardVolumeMounts(),
	}
}
